#!/bin/bash
# =============================================================================
# 02.1-configure-agentcore.sh
# Configures the Restaurant Menu Agent for AgentCore Runtime deployment
# Reads Cognito values from .cognito-config generated by 01-setup-cognito.sh
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
AGENT_DIR="${PROJECT_ROOT}/agent"

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

print_status() { echo -e "${GREEN}[INFO]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }
print_header() { echo -e "${BLUE}[STEP]${NC} $1"; }

# ─── Load Cognito config from Step 1 ─────────────────────────────────────────
if [ ! -f "${SCRIPT_DIR}/.cognito-config" ]; then
    print_error "Missing .cognito-config — run 01-setup-cognito.sh first"
    exit 1
fi

source "${SCRIPT_DIR}/.cognito-config"

# Validate required values
if [ -z "$USER_POOL_ID" ] || [ -z "$WEBUI_CLIENT_ID" ] || [ -z "$REGION" ]; then
    print_error ".cognito-config is incomplete. Re-run 01-setup-cognito.sh"
    exit 1
fi

print_status "Loaded Cognito config from .cognito-config"
print_status "  User Pool ID : $USER_POOL_ID"
print_status "  Client ID    : $WEBUI_CLIENT_ID"
print_status "  Region       : $REGION"

# ─── Build authorizer config ─────────────────────────────────────────────────
PROJECT_NAME="restaurant_menu_agent"
COGNITO_DISCOVERY_URL="https://cognito-idp.${REGION}.amazonaws.com/${USER_POOL_ID}/.well-known/openid-configuration"
AUTHORIZER_CONFIG="{\"customJWTAuthorizer\":{\"discoveryUrl\":\"${COGNITO_DISCOVERY_URL}\",\"allowedClients\":[\"${WEBUI_CLIENT_ID}\"]}}"

# ─── Configure AgentCore ──────────────────────────────────────────────────────
print_header "Configuring AgentCore for deployment"

cd "$AGENT_DIR"

agentcore configure \
    --entrypoint main.py \
    --name "$PROJECT_NAME" \
    --region "$REGION" \
    --deployment-type container \
    --authorizer-config "$AUTHORIZER_CONFIG" \
    --request-header-allowlist "Authorization,X-Amzn-Bedrock-AgentCore-Runtime-Custom-TenantId,X-Amzn-Bedrock-AgentCore-Runtime-Custom-ActorId"

print_status "AgentCore configured successfully"
print_status "Configuration saved to: ${AGENT_DIR}/.bedrock_agentcore.yaml"
echo ""
echo "  Next step: Run 02.2-launch-agentcore.sh to deploy"
